import turtle
mypen = turtle.Pen()
mypen.penup()
mypen.goto(-100,-100)
mypen.pendown()
mypen.lt(90)
mypen.fillcolor("lightgray")
mypen.begin_fill()
for i in range(4):
    mypen.fd(200)
    mypen.rt(90)
mypen.end_fill()
mypen.fillcolor("beige")
mypen.fd(250)

mypen.rt(90)
mypen.fd(60)
mypen.rt(90)
mypen.fd(50)
mypen.lt(90)
mypen.fd(80)
mypen.lt(90)
mypen.fd(50)
mypen.rt(90)
mypen.fd(60)
mypen.rt(90)
mypen.fd(50)
mypen.penup()
mypen.home()
mypen.pendown()

mypen.begin_fill()
mypen.bk(60)
for i in range(3):
    mypen.fd(120)
    mypen.rt(90)
    mypen.fd(80)
    mypen.rt(90)
mypen.end_fill()
mypen.fillcolor("black")
mypen.begin_fill()
mypen.fd(120)
for i in range(2):
    mypen.rt(90)
    mypen.fd(10)
    mypen.rt(90)
    mypen.fd(120)
mypen.end_fill()
mypen.fillcolor("beige")
mypen.begin_fill()
mypen.rt(90)
mypen.fd(80)
mypen.rt(90)
mypen.end_fill()



mypen.fillcolor("black")
mypen.begin_fill()
mypen.fd(40)
mypen.rt(90)
mypen.fd(30)
mypen.lt(90)
mypen.fd(40)
mypen.lt(90)
mypen.fd(30)

mypen.end_fill()
mypen.home()
mypen.lt(90)
mypen.penup()
mypen.fd(50)
mypen.rt(90)
mypen.fd(40)
mypen.pendown()
mypen.begin_fill()
for i in range(4):
    mypen.fd(15)
    mypen.rt(90)
mypen.end_fill()
mypen.penup()
mypen.home()
mypen.lt(90)
mypen.fd(50)
mypen.lt(90)
mypen.fd(40)

mypen.pendown()
mypen.begin_fill()
for i in range(4):
    mypen.fd(15)
    mypen.lt(90)
mypen.end_fill()

mypen.ht()
